---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: crossbar
    name: crossbar
  name: crossbar
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: crossbar
  template:
    metadata:
      labels:
        k8s-app: crossbar
    spec:
      containers:
      - name: crossbar
        image: crossbario/crossbar
        imagePullPolicy: Always
