apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pg-buildbot
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: pg-buildbot
    spec:
      containers:
      - image: postgres
        name: pg
        env:
        - name: POSTGRES_DB
          value: buildbot

        - name: POSTGRES_USER
          value: buildbot

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: buildbot
              key: pg_password
        ports:
        - containerPort: 5432
          name: pg
        volumeMounts:
        - name: pg-buildbot
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg-buildbot
        persistentVolumeClaim:
          claimName: pg-buildbot
